# Generated by Django 2.0.13 on 2020-02-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200208_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_policy', models.TextField()),
            ],
        ),
    ]
