# Generated by Django 2.0.13 on 2020-02-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200209_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constants',
            name='add_age_restriction_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constants',
            name='add_device_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='constants',
            name='add_information',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='constants',
            name='add_opt_out_links',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='constants',
            name='add_order_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='constants',
            name='add_payment_types',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='constants',
            name='add_remarketing',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='constants',
            name='add_tracking',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
