# Generated by Django 2.0.13 on 2020-02-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20200209_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplePolicys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('site_name', models.URLField()),
                ('add_tracking', models.CharField(blank=True, max_length=200, null=True)),
                ('add_payment_types', models.CharField(blank=True, max_length=200, null=True)),
                ('add_information', models.CharField(blank=True, max_length=200, null=True)),
                ('add_order_info', models.CharField(blank=True, max_length=200, null=True)),
                ('add_device_info', models.CharField(blank=True, max_length=200, null=True)),
                ('add_remarketing', models.CharField(blank=True, max_length=200, null=True)),
                ('add_opt_out_links', models.CharField(blank=True, max_length=200, null=True)),
                ('add_europe', models.BooleanField(default=False)),
                ('add_age_restriction_age', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('street_address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='SamplePolicy',
        ),
    ]
